services:
  file-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./static/generated_files:/app/static/generated_files
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
